# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Theme Config
ZSH_THEME="powerlevel9k/powerlevel9k"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(virtualenv dir dir_writable vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status time)
POWERLEVEL9K_VIRTUALENV_BACKGROUND=white

# Prevent VirtualEnv from interfering.
NODE_VIRTUAL_ENV_DISABLE_PROMPT=1


plugins=(git zsh-navigation-tools z)

source $ZSH/oh-my-zsh.sh

export TERM='xterm-256color' #Force

if [ -f ~/.zshrc.local ]; then
  source ~/.zshrc.local
fi
